# Generated by Django 4.0.10 on 2023-10-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_course_section_subsection_unit_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsection',
            old_name='Section',
            new_name='section',
        ),
    ]
