# Generated by Django 4.0.10 on 2023-10-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_section_subsection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.PositiveIntegerField(default=148291),
        ),
    ]
