# Generated by Django 4.0.10 on 2023-10-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAndOtp',
        ),
    ]
